# Generated by Django 3.2.7 on 2021-11-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_published',
        ),
        migrations.AddField(
            model_name='poll',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
